name: nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore
    - name: Pack nuget library
      run: dotnet pack src/FM.LiveSwitch.Mux.Standard/FM.LiveSwitch.Mux.Standard.csproj -c Release -o artifacts/nuget
    - name: Push nuget library
      run: dotnet nuget push artifacts/nuget/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
